/*
    Simple http-client written to be an drop-in code, focus is to be small
    and easy to use but maybe not efficient.

    version 1.0, June, 2014

	Copyright (C) 2014- Fredrik Kihlander

	This software is provided 'as-is', without any express or implied
	warranty.  In no event will the authors be held liable for any damages
	arising from the use of this software.

	Permission is granted to anyone to use this software for any purpose,
	including commercial applications, and to alter it and redistribute it
	freely, subject to the following restrictions:

	1. The origin of this software must not be misrepresented; you must not
	   claim that you wrote the original software. If you use this software
	   in a product, an acknowledgment in the product documentation would be
	   appreciated but is not required.
	2. Altered source versions must be plainly marked as such, and must not be
	   misrepresented as being the original software.
	3. This notice may not be removed or altered from any source distribution.

	Fredrik Kihlander
*/

#ifndef HTTP_CLIENT_ERROR_H_INCLUDED
#define HTTP_CLIENT_ERROR_H_INCLUDED

/**
 * Error codes used by http_client_t and its functions.
 *
 * All http-error-codes should be mapped to their numeric counterparts in this enum.
 * I.e. HTTP_CLIENT_RESULT_404_NOT_FOUND has the value 404.
 */
enum http_client_result
{
	HTTP_CLIENT_OK,
	HTTP_CLIENT_INVALID_URL,
	HTTP_CLIENT_UNSUPPORTED_SCHEME,
	HTTP_CLIENT_SOCKET_ERROR, // flesh out this.
	HTTP_CLIENT_CONNECTION_LOST,
	HTTP_CLIENT_MEMORY_ALLOC_ERROR,
	HTTP_CLIENT_INTERNAL_ERROR,

	// will I need these error-codes, or should re-direct be handled internally?
	HTTP_CLIENT_RESULT_300_MULTIPLE_CHOICES = 300,
	HTTP_CLIENT_RESULT_301_MOVED_PERMANENTLY,
	HTTP_CLIENT_RESULT_302_FOUND,
	HTTP_CLIENT_RESULT_303_SEE_OTHER,
	HTTP_CLIENT_RESULT_304_NOT_MODIFIED,
	HTTP_CLIENT_RESULT_305_USE_PROXY,
	HTTP_CLIENT_RESULT_306_SWITCH_PROXY,
	HTTP_CLIENT_RESULT_307_TEMPORARY_REDIRECT,
	HTTP_CLIENT_RESULT_308_PERMANENT_REDIRECT,

	HTTP_CLIENT_RESULT_400_BAD_REQUEST = 400,
	HTTP_CLIENT_RESULT_401_UNAUTHORIZED,
	HTTP_CLIENT_RESULT_402_PAYMENT_REQUIRED,
	HTTP_CLIENT_RESULT_403_FORBIDDEN,
	HTTP_CLIENT_RESULT_404_NOT_FOUND,
	HTTP_CLIENT_RESULT_405_METHOD_NOT_ALLOWED,
	HTTP_CLIENT_RESULT_406_NOT_ACCEPTABLE,
	HTTP_CLIENT_RESULT_407_PROXY_AUTHENTICATION_REQUIRED,
	HTTP_CLIENT_RESULT_408_REQUEST_TIMEOUT,
	HTTP_CLIENT_RESULT_409_CONFLICT,
	HTTP_CLIENT_RESULT_410_GONE,
	HTTP_CLIENT_RESULT_411_LENGTH_REQUIRED,
	HTTP_CLIENT_RESULT_412_PRECONDITION_FAILED,
	HTTP_CLIENT_RESULT_413_REQUEST_ENTITY_TOO_LARGE,
	HTTP_CLIENT_RESULT_414_REQUEST_URI_TOO_LONG,
	HTTP_CLIENT_RESULT_415_UNSUPPORTED_MEDIA_TYPE,
	HTTP_CLIENT_RESULT_416_REQUESTED_RANGE_NOT_SATISFIABLE,
	HTTP_CLIENT_RESULT_417_EXPECTATION_FAILED,
	HTTP_CLIENT_RESULT_418_IM_A_TEAPOT,
	HTTP_CLIENT_RESULT_419_AUTHENTICATION_TIMEOUT,

	// Spring_Framework
	HTTP_CLIENT_RESULT_420_METHOD_FAILURE = 420,

	// Twitter
	HTTP_CLIENT_RESULT_420_ENHANCE_YOUR_CALM = 420,

	// WebDAV RFC 4918
	HTTP_CLIENT_RESULT_422_UNPROCESSABLE_ENTITY = 422,
	HTTP_CLIENT_RESULT_423_LOCKED,
	HTTP_CLIENT_RESULT_424_FAILED_DEPENDENCY,

	// Internet_draft
	HTTP_CLIENT_RESULT_425_UNORDERED_COLLECTION = 425,
	HTTP_CLIENT_RESULT_451_UNAVAILABLE_FOR_LEGAL_REASONS = 451,

	// RFC_2817
	HTTP_CLIENT_RESULT_426_UPGRADE_REQUIRED = 426,

	// RFC_6585
	HTTP_CLIENT_RESULT_428_PRECONDITION_REQUIRED = 428,
	HTTP_CLIENT_RESULT_429_TOO_MANY_REQUESTS = 429,
	HTTP_CLIENT_RESULT_431_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,

	// Microsoft
	HTTP_CLIENT_RESULT_440_LOGIN_TIMEOUT = 440,
	HTTP_CLIENT_RESULT_449_RETRY_WITH = 449,
	HTTP_CLIENT_RESULT_450_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450,
	HTTP_CLIENT_RESULT_451_REDIRECT = 451,

	// Nginx
	HTTP_CLIENT_RESULT_444_NO_RESPONSE = 444,
	HTTP_CLIENT_RESULT_494_REQUEST_HEADER_TOO_LARGE = 494,
	HTTP_CLIENT_RESULT_495_CERT_ERROR,
	HTTP_CLIENT_RESULT_496_NO_CERT,
	HTTP_CLIENT_RESULT_497_HTTP_TO_HTTPS,
	HTTP_CLIENT_RESULT_499_CLIENT_CLOSED_REQUEST = 499,

	HTTP_CLIENT_RESULT_500_INTERNAL_SERVER_ERROR = 500,
	HTTP_CLIENT_RESULT_501_NOT_IMPLEMENTED,
	HTTP_CLIENT_RESULT_502_BAD_GATEWAY,
	HTTP_CLIENT_RESULT_503_SERVICE_UNAVAILABLE,
	HTTP_CLIENT_RESULT_504_GATEWAY_TIMEOUT,
	HTTP_CLIENT_RESULT_505_HTTP_VERSION_NOT_SUPPORTED,
	HTTP_CLIENT_RESULT_506_VARIANT_ALSO_NEGOTIATES,
	HTTP_CLIENT_RESULT_507_INSUFFICIENT_STORAGE,
	HTTP_CLIENT_RESULT_508_LOOP_DETECTED,
	HTTP_CLIENT_RESULT_509_BANDWIDTH_LIMIT_EXCEEDED,
	HTTP_CLIENT_RESULT_510_NOT_EXTENDED,
	HTTP_CLIENT_RESULT_511_NETWORK_AUTHENTICATION_REQUIRED,
	HTTP_CLIENT_RESULT_520_ORIGIN_ERROR = 520,
	HTTP_CLIENT_RESULT_521_WEB_SERVER_IS_DOWN,
	HTTP_CLIENT_RESULT_522_CONNECTION_TIMED_OUT,
	HTTP_CLIENT_RESULT_523_PROXY_DECLINED_REQUEST,
	HTTP_CLIENT_RESULT_524_A_TIMEOUT_OCCURRED,
	HTTP_CLIENT_RESULT_598_NETWORK_READ_TIMEOUT_ERROR = 598,
	HTTP_CLIENT_RESULT_599_NETWORK_CONNECT_TIMEOUT_ERROR
};

#endif // HTTP_CLIENT_ERROR_H_INCLUDED
